package com.plusmobileapps.chefmate.recipe.core.root

import com.arkivanov.decompose.router.stack.ChildStack
import com.arkivanov.decompose.value.Value
import com.arkivanov.essenty.backhandler.BackHandlerOwner
import com.plusmobileapps.chefmate.BackClickBloc
import com.plusmobileapps.chefmate.BlocContext
import com.plusmobileapps.chefmate.Consumer
import com.plusmobileapps.chefmate.recipe.core.addmeal.MealPlannerRootBloc
import com.plusmobileapps.chefmate.recipe.core.detail.RecipeDetailBloc
import com.plusmobileapps.chefmate.recipe.core.edit.EditRecipeBloc
import com.plusmobileapps.chefmate.recipe.data.ExtractedRecipeData
import com.plusmobileapps.chefmate.ui.BlocScreen
import kotlinx.serialization.Serializable

interface RecipeRootBloc : BackHandlerOwner, BackClickBloc, BlocScreen {
    val routerState: Value<ChildStack<*, Child>>

    sealed class Child : BlocScreen {
        data class Detail(val bloc: RecipeDetailBloc) : Child(), BlocScreen by bloc

        data class Edit(val bloc: EditRecipeBloc) : Child(), BlocScreen by bloc
    }

    sealed class Output {
        data object Finished : Output()

        data class OpenUrl(val url: String) : Output()

        data object OpenGroceryList : Output()

        data class OpenMealPlanner(val props: MealPlannerRootBloc.Props) : Output()

        data class OpenCookMode(val recipeId: Long) : Output()
    }

    @Serializable
    sealed class Props {
        @Serializable data class Detail(val recipeId: Long) : Props()

        @Serializable data object Create : Props()

        @Serializable
        data class CreateFromExtracted(
            val extracted: ExtractedRecipeData,
            /**
             * When true, the recipe was generated by AI chat and is auto-tagged with the AI
             * category.
             */
            val fromAi: Boolean = false,
            /**
             * When true, the Edit Recipe screen pulls the photo that was picked for extraction from
             * [com.plusmobileapps.chefmate.recipe.data.PendingRecipePhotoStore] and pre-fills it as
             * the pending recipe image.
             */
            val consumePendingPhoto: Boolean = false,
        ) : Props()
    }

    fun interface Factory {
        fun create(context: BlocContext, props: Props, output: Consumer<Output>): RecipeRootBloc
    }
}
